# Generated by Django 4.2.3 on 2024-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_realtor',
            field=models.BooleanField(default=False),
        ),
    ]
