# Generated by Django 4.2.3 on 2024-08-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=255, unique=True)),
                ('sender_object_id', models.PositiveIntegerField()),
                ('receiver_object_id', models.PositiveIntegerField()),
                ('receiver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_receiver', to='contenttypes.contenttype')),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sender', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ['date'],
            },
        ),
    ]
