# Generated by Django 4.2.3 on 2024-08-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_receiver_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_content_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_object_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_object_id',
        ),
    ]
