# Generated by Django 4.2.3 on 2024-08-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0005_remove_chatmessage_receiver_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='current_receiver_content_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_receiver_object_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_sender_content_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_sender_object_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
