# Generated by Django 4.2.3 on 2024-08-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatsession_current_receiver_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='receiver_content_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='receiver_object_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='sender_object_id',
        ),
    ]
