# Generated by Django 4.2.3 on 2024-08-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
