# Generated by Django 4.2.3 on 2024-08-09 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=225, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('garden', models.PositiveIntegerField(null=True)),
                ('floor', models.PositiveIntegerField(null=True)),
                ('kitchen', models.PositiveIntegerField(null=True)),
                ('bathrooms', models.PositiveIntegerField(null=True)),
                ('sqrft', models.PositiveIntegerField(null=True)),
                ('garage', models.PositiveIntegerField(null=True)),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_7', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
        migrations.CreateModel(
            name='RentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=225, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('garden', models.PositiveIntegerField(null=True)),
                ('floor', models.PositiveIntegerField(null=True)),
                ('kitchen', models.PositiveIntegerField(null=True)),
                ('bathrooms', models.PositiveIntegerField(null=True)),
                ('garage', models.PositiveIntegerField(default=0, null=True)),
                ('sqrft', models.PositiveIntegerField(null=True)),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo_7', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
