# Generated by Django 4.2.3 on 2024-08-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='promotion_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='promotion_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='is_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='promotion_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='promotion_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
