# Generated by Django 4.2.3 on 2024-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_rentlisting_is_promotion_rentlisting_promotion_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlisting',
            name='color',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='colorHex',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='rentlisting',
            name='originalPrice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='originalPrice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
