# Generated by Django 4.2.3 on 2024-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_rentlisting_color_rentlisting_colorhex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelisting',
            name='color',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='salelisting',
            name='colorHex',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
